# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b9a8d692ba5f40692df1f44eb64b10bebb5d95a84f5be5fb05e3f7520e5a55b23b67c7862e3553c687ab70ff48f6917cff39d9d33a3ca53a419ff40ed90bbef

test:
  secret_key_base: 7b0c92fa8da805a2a35a42ef251349c628847994761c3bb29f65d61e67b2a76c6054ec70b8fcc1d1de7a57f0f086e98896aa20e46aeaa4bfe71a61c875ff10fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
